ExamTemplate/Web/Models/ErrorViewModel.cs
namespace ExamTemplate.Web.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
	}
}

ExamTemplate/Web/Models/User/LoginUserViewModel.cs
namespace ExamTemplate.Web.Models.User
{
	public class LoginUserViewModel
	{
		public string Username { get; set; }
		public string Password { get; set; }
	}
}

ExamTemplate/Web/Models/User/RegisterUserViewModel.cs
namespace ExamTemplate.Web.Models.User
{
	public class RegisterUserViewModel
	{
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Username { get; set; }
		public string Password { get; set; }
	}
}

ExamTemplate/Web/Controllers/HomeController.cs
using System.Diagnostics;
using ExamTemplate.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ExamTemplate.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			this._logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
		}
	}
}

ExamTemplate/Web/Controllers/UserController.cs
using ExamTemplate.Services;
using Microsoft.AspNetCore.Mvc;
using ExamTemplate.Web.Models.User;
using AutoMapper;
using ExamTemplate.Services.Models;
using System.Threading.Tasks;

namespace ExamTemplate.Web.Controllers
{
	public class UserController : Controller
	{
		private readonly IMapper _autoMapper;
		private readonly UserService _userService;

		public UserController(IMapper autoMapper, UserService userService)
		{
			this._autoMapper = autoMapper;
			this._userService = userService;
		}

		[HttpGet]
		[Route("/Register")]
		public IActionResult Register()
		{
			return View();
		}

		[HttpPost]
		[Route("/Register")]
		public async Task<IActionResult> Register(RegisterUserViewModel registerUserViewModel)
		{
			RegisterUserServiceModel registerUserServiceModel = this._autoMapper.Map<RegisterUserServiceModel>(registerUserViewModel);

			bool result = await this._userService.RegisterUserAsync(registerUserServiceModel);

			if (result)
				return RedirectToAction("Index", "Home");
			else
				return View();
		}

		[HttpGet]
		[Route("/Login")]
		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		[Route("/Login")]
		public async Task<IActionResult> Login(LoginUserViewModel loginUserViewModel)
		{
			LoginUserServiceModel loginUserServiceModel = this._autoMapper.Map<LoginUserServiceModel>(loginUserViewModel);

			bool result = await this._userService.LoginUserAsync(loginUserServiceModel);

			if (result)
				return RedirectToAction("Index", "Home");
			else
				return View();
		}

		[HttpPost]
		public async Task<IActionResult> Logout()
		{
			await this._userService.LogoutAsync();

			return RedirectToAction("Login");
		}
	}
}

ExamTemplate/Web/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Welcome</h1>
	<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamTemplate/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Web</title>
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>
	<header>
		<partial name="_Navbar.cshtml" />
	</header>

	<main class="main">
		<div class="middle-content-container">
			@RenderBody()
		</div>
	</main>

	<footer class="border-top box-shadow">
		<div class="middle-content-container">
			&copy; 2021 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
</body>
</html>

ExamTemplate/Web/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<nav class="navbar border-bottom box-shadow">
	<div class="middle-content-container navbar-contents">
		<section>
			<b>
				<a asp-controller="Home" asp-action="Index">Web</a>
			</b>
			<a asp-controller="Home" asp-action="Index">Home</a>
			<a asp-controller="Home" asp-action="Privacy">Privacy</a>
		</section>
		<div class="flex-spacer"></div>
		<section>
			@if (SignInManager.IsSignedIn(User))
			{
				<a asp-controller="User" asp-action="">@UserManager.GetUserName(User)</a>

				<form asp-controller="User" asp-action="Logout" method="post">
					<input type="submit" value="Logout">
				</form>
			}
			else
			{
				<a asp-controller="User" asp-action="Login">Login</a>
				<a asp-controller="User" asp-action="Register">Register</a>
			}
		</section>
	</div>
</nav>

ExamTemplate/Web/Views/User/Login.cshtml
@model ExamTemplate.Web.Models.User.LoginUserViewModel
@{
    ViewData["Title"] = "Login";
}

<form asp-controller="User" asp-action="Login" method="post">
	<input type="text" asp-for="Username" placeholder="Username">
	<input type="password" asp-for="Password" placeholder="Password">
	<input type="submit">
</form>

ExamTemplate/Web/Views/User/Register.cshtml
@model ExamTemplate.Web.Models.User.RegisterUserViewModel
@{
    ViewData["Title"] = "Register";
}

<form asp-controller="User" asp-action="Register" method="post">
	<input type="text" asp-for="FirstName" placeholder="FirstName">
	<input type="text" asp-for="LastName" placeholder="LastName">
	<input type="text" asp-for="Username" placeholder="Username">
	<input type="password" asp-for="Password" placeholder="Password">
	<input type="submit">
</form>